######   PLAY 2  #######

- name: 2 - Configure Eventstore image
#  hosts: localhost
#  connection: local
  hosts: eventstore:&{{ env_id }}
  gather_facts: true

  vars_files:
    - secrets.yml

  tasks:
#  - name: Fetch ES setup script from repo
#    get_url:
#      url: "https://{{ eventstore_slice_token }}:@packagecloud.io/install/repositories/EventStore/EventStore-HA/script.rpm.sh"
#      dest: ./
#      mode: 0755
#      force: yes
# TODO: the above commented block won't work without a password, so use the following 2 commands until get_url is fixed
  - name: Fetch ES setup script from repo
    shell: "curl https://{{ eventstore_slice_token }}:@packagecloud.io/install/repositories/EventStore/EventStore-HA/script.rpm.sh > ./eventstore.rpm.sh"

  - name: Make script executable
    file:
      path: ./eventstore.rpm.sh
      mode: 0755

  - name: Execute the Eventstore setup script
    shell: ./eventstore.rpm.sh
    become: true

  - name: Install needed packages
    yum: pkg={{ item }} state=latest update_cache=true
    with_items:
    - eventstore-ha-aws
    - jq
    become: true


