---
- name: Install epel release
  yum: name="epel-release" state=latest
  become: true
- name: Update system
  yum: name=* state=latest
  ignore_errors: true
  become: true
- name: Install needed packages
  yum: pkg={{ item }} state=latest
  with_items:
  - git
  - gcc
  - openssl-devel
  - libffi-devel
  - libjpeg-devel
  - freetds-devel
  - MySQL-python
  - mysql-devel
  become: true
...