---
ansible_connection: local
ansible_python_interpreter: python

env_name: OPS03
env_type: dev

region: us-east-2
vpc_cdir: 10.56.0.0/16
access_vpc_cidr: 172.30.0.0/16

restricted_access: true
detailed_monitoring: false
autoscaling: false

vpc_public_subnets: ['10.56.0.0/21', '10.56.8.0/21']
vpc_private_subnets: ['10.56.192.0/19', '10.56.224.0/19']
vpc_db_subnets: ['10.56.16.0/21', '10.56.32.0/21']

product_ami: ami-6fe5c00a
product_instance_type: t2.large
product_inst_min: 1
product_inst_max: 2
product_keypair: ops03-ohio

idm_ami: ami-6fe5c00a
idm_instance_type: t2.large
idm_inst_min: 1
idm_inst_max: 2
idm_keypair: ops03-ohio

uw_services_ami: ami-6fe5c00a
uw_services_instance_type: t2.large
uw_services_inst_min: 1
uw_services_inst_max: 2
uw_services_keypair: ops03-ohio

claims_ami: ami-6fe5c00a
claims_instance_type: t2.medium
claims_inst_min: 1
claims_inst_max: 2
claims_keypair: ops03-ohio

claims_web_ami: ami-6fe5c00a
claims_web_instance_type: t2.medium
claims_web_inst_min: 1
claims_web_inst_max: 2
claims_web_keypair: ops03-ohio

product_web_ami: ami-910025f4
product_web_instance_type: t2.medium
product_web_inst_min: 1
product_web_inst_max: 2
product_web_keypair: ops03-ohio

eventstore_ami: ami-73002516
eventstore_instance_type: m4.large
eventstore_inst_min: 1
eventstore_inst_max: 1
eventstore_keypair: ops03-ohio

notifications_ami: ami-3a5e785f
notifications_instance_type: t2.large
notifications_inst_min: 1
notifications_inst_max: 1
notifications_keypair: ops03-ohio

ssl_certificate_arn: "arn:aws:acm:us-east-2:516087258462:certificate/fa004f29-0092-4d7d-9e30-c69d95550fa1"    # May 2017
