---
ansible_connection: local
ansible_python_interpreter: python

env_name: OPS01
env_type: 1-ops

region: us-east-2
s3_website_region: "{{ region }}"
vpc_cdir: 10.16.0.0/16
access_vpc_cidr: 172.29.0.0/16

restricted_access: true
detailed_monitoring: false
autoscaling: true

vpc_public_subnets: ['10.16.0.0/21', '10.16.8.0/21']
vpc_private_subnets: ['10.16.192.0/19', '10.16.224.0/19']
vpc_db_subnets: ['10.16.16.0/21', '10.16.32.0/21']

product_ami: ami-10547475
product_instance_type: t2.micro
product_inst_min: 1
product_inst_max: 2
product_keypair: ops01-central

#
#idm_ami: ami-48a0335e
#idm_instance_type: t2.large
#idm_inst_min: 1
#idm_inst_max: 2
#idm_keypair: ops01-oregon
#
#uw_services_ami: ami-48a0335e
#uw_services_instance_type: t2.large
#uw_services_inst_min: 1
#uw_services_inst_max: 2
#uw_services_keypair: ops01-oregon
#
#claims_ami: ami-48a0335e
#claims_instance_type: t2.medium
#claims_inst_min: 1
#claims_inst_max: 2
#claims_keypair: ops01-oregon
#
#claims_web_ami: ami-82b12294
#claims_web_instance_type: t2.medium
#claims_web_inst_min: 1
#claims_web_inst_max: 2
#claims_web_keypair: ops01-oregon

#product_web_ami: ami-c26e09a2
#product_web_instance_type: t2.small
#product_web_inst_min: 0
#product_web_inst_max: 2
## product_web_inst_desired:
#product_web_keypair: ops01-oregon

#eventstore_ami: ami-9606fbfb
#eventstore_instance_type: m4.large
#eventstore_inst_min: 1
#eventstore_inst_max: 1
#eventstore_keypair: ops01-oregon
#
#website_ami: ami-c95ec7df
#website_instance_type: t2.medium
#website_inst_min: 0
#website_inst_max: 1
#website_keypair: ops01-oregon

ssl_certificate_arn: "arn:aws:acm:us-west-2:516087258462:certificate/b7d30202-3bfe-4bc6-bd4e-fa79bf1ff770"    # May 2017

instance_roles:
- name: product
  ami: ami-a69af7c6
  instance_type: t2.large
  inst_min: 1
  inst_max: 2
  instance_profile_name: Deploy-Slice-Core-EC2
  key_name: ops01-oregon

#- name: idm
#  ami: ami-a69af7c6
#  instance_type: t2.large
#  inst_min: 1
#  inst_max: 2
#  instance_profile_name: Deploy-Slice-Core-EC2
#  keypair: ops01-oregon

#- name: uw_services
#  ami: ami-a69af7c6
#  instance_type: t2.large
#  inst_min: 1
#  inst_max: 2
#  instance_profile_name: Deploy-Slice-Core-EC2
#  keypair: ops01-oregon
