---
ansible_connection: local
ansible_python_interpreter: python

env_name: STG03
env_type: dev

region: eu-central-1
vpc_cdir: 10.35.0.0/16
access_vpc_cidr: 172.27.0.0/16

restricted_access: true
detailed_monitoring: false
autoscaling: false

vpc_public_subnets: ['10.35.0.0/21', '10.35.8.0/21']
vpc_private_subnets: ['10.35.192.0/19', '10.35.224.0/19']
vpc_db_subnets: ['10.35.16.0/21', '10.35.32.0/21']

product_ami: ami-78439817
product_instance_type: t2.large
product_inst_min: 1
product_inst_max: 2
product_keypair: stg03-frankfurt

idm_ami: ami-78439817
idm_instance_type: t2.large
idm_inst_min: 1
idm_inst_max: 2
idm_keypair: stg03-frankfurt

uw_services_ami: ami-78439817
uw_services_instance_type: t2.large
uw_services_inst_min: 1
uw_services_inst_max: 2
uw_services_keypair: stg03-frankfurt

claims_ami: ami-78439817
claims_instance_type: t2.medium
claims_inst_min: 1
claims_inst_max: 2
claims_keypair: stg03-frankfurt

claims_web_ami: ami-32479c5d
claims_web_instance_type: t2.medium
claims_web_inst_min: 1
claims_web_inst_max: 2
claims_web_keypair: stg03-frankfurt

product_web_ami: ami-c0419aaf
product_web_instance_type: t2.medium
product_web_inst_min: 1
product_web_inst_max: 2
product_web_keypair: stg03-frankfurt

eventstore_ami: ami-e34c978c
eventstore_instance_type: m4.large
eventstore_inst_min: 1
eventstore_inst_max: 1
eventstore_keypair: stg03-frankfurt

#website_ami: ami-58f1814e
#website_instance_type: t2.medium
#website_inst_min: 1
#website_inst_max: 2
#website_keypair: stg03-frankfurt

notifications_ami: ami-78439817
notifications_instance_type: t2.large
notifications_inst_min: 1
notifications_inst_max: 1
notifications_keypair: stg03-frankfurt

ssl_certificate_arn: "arn:aws:acm:eu-central-1:516087258462:certificate/7ea6d756-f992-4635-bd19-8646d798ea77"    # May 2017
