---
ansible_connection: local
ansible_python_interpreter: python

env_name: TST03
env_type: dev

region: eu-west-2
vpc_cdir: 10.86.0.0/16
access_vpc_cidr: 172.26.0.0/16

restricted_access: true
detailed_monitoring: true
autoscaling: false

vpc_public_subnets: ['10.86.0.0/21', '10.86.8.0/21']
vpc_private_subnets: ['10.86.192.0/19', '10.86.224.0/19']
vpc_db_subnets: ['10.86.16.0/21', '10.86.32.0/21']

product_ami: ami-cb1e09af
product_instance_type: t2.large
product_inst_min: 1
product_inst_max: 2
product_keypair: tst03-london

idm_ami: ami-661f0802
idm_instance_type: t2.large
idm_inst_min: 1
idm_inst_max: 2
idm_keypair: tst03-london

uw_services_ami: ami-171d0a73
uw_services_instance_type: t2.large
uw_services_inst_min: 1
uw_services_inst_max: 2
uw_services_keypair: tst03-london

claims_ami: ami-d71c0bb3
claims_instance_type: t2.medium
claims_inst_min: 1
claims_inst_max: 2
claims_keypair: tst03-london

claims_web_ami: ami-d61c0bb2
claims_web_instance_type: t2.medium
claims_web_inst_min: 1
claims_web_inst_max: 2
claims_web_keypair: tst03-london

product_web_ami: ami-d41c0bb0
product_web_instance_type: t2.medium
product_web_inst_min: 1
product_web_inst_max: 2
product_web_keypair: tst03-london

eventstore_ami: ami-12100776
eventstore_instance_type: m4.large
eventstore_inst_min: 1
eventstore_inst_max: 1
eventstore_keypair: tst03-london

notifications_ami: ami-cad1c6ae
notifications_instance_type: t2.large
notifications_inst_min: 1
notifications_inst_max: 1
notifications_keypair: tst03-london

ssl_certificate_arn: "arn:aws:acm:eu-west-2:516087258462:certificate/0c165204-f177-4cdd-a289-1499af7d2db4"    # Wildcard May 2017
